name: BryansFirstSite
favicon: null
layout_spectrum: 0.4281922564841807
typography_spectrum: 0.5779386963695288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1350478653330356
  lightness: 0.9353093432728201
  saturation: 0.5454455639701337
  rhythmicContrast: 0.5526593362446874
purpose: []
